from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import pandas as pd


# ============================================================
# AURA DATA LOGGER
# ============================================================
#
# Central persistence layer for AURA Privacy Guardian.
#
# Responsibilities:
#
#   • Store security telemetry
#   • Store AI detection results
#   • Store privacy intelligence
#   • Store unified risk scores
#   • Maintain the ML baseline
#   • Maintain compatibility with older AURA logs
#
# The logger does NOT read file contents or network payloads.
# It stores telemetry generated by the AURA monitoring engine.
#
# ============================================================


# ============================================================
# PATH CONFIGURATION
# ============================================================

BASE_DIR = Path(
    __file__
).resolve().parent

DATA_DIR = (
    BASE_DIR / "data"
)

LOG_FILE = (
    DATA_DIR / "system_logs.csv"
)

BASELINE_FILE = (
    DATA_DIR / "baseline.csv"
)


# ============================================================
# BASELINE SCHEMA
# ============================================================

BASELINE_COLUMNS = [
    "CPU",
    "Net",
    "Cam",
]


# ============================================================
# AURA LOG SCHEMA
# ============================================================
#
# Keep the original columns so the current dashboard remains
# compatible.
#
# Additional columns support the upgraded AURA engine.
# ============================================================

COLUMNS = [

    # --------------------------------------------------------
    # Event metadata
    # --------------------------------------------------------

    "Timestamp",
    "Event_ID",

    # --------------------------------------------------------
    # Primary sensors
    # --------------------------------------------------------

    "CPU",
    "Net",
    "Cam",

    "Memory",
    "Disk",

    "Disk_Read",
    "Disk_Write",

    "CPU_Frequency",

    # --------------------------------------------------------
    # Network telemetry
    # --------------------------------------------------------

    "Network_Download",
    "Network_Upload",

    "Process_Count",

    "Remote_Connections",
    "Established_Connections",
    "Listening_Connections",

    # --------------------------------------------------------
    # Privacy inventory
    # --------------------------------------------------------

    "Sensitive_Files",

    # --------------------------------------------------------
    # AI detection
    # --------------------------------------------------------

    "IF_Anomaly",
    "LOF_Anomaly",
    "Anomaly",

    "IF_Score",
    "LOF_Score",

    "IF_Anomaly_Intensity",
    "LOF_Anomaly_Intensity",

    "Anomaly_Confidence",

    "Strongest_Feature",
    "Strongest_Feature_Deviation",

    # --------------------------------------------------------
    # Risk intelligence
    # --------------------------------------------------------

    "Risk",
    "Severity",
    "Risk_Score",

    "Network_Level",
    "Process_Level",

    "Privacy_Event",

    "Potential_Data_Exfiltration",
    "Potential_Camera_Risk",

    # --------------------------------------------------------
    # Behaviour intelligence
    # --------------------------------------------------------

    "Behavioral_Adjustment",

    # --------------------------------------------------------
    # Model information
    # --------------------------------------------------------

    "Model_Health",
    "Training_Samples",

]


# ============================================================
# DEFAULT VALUES
# ============================================================

DEFAULTS: dict[str, Any] = {

    "Timestamp": "",
    "Event_ID": "",

    "CPU": 0.0,
    "Net": 0.0,
    "Cam": 0,

    "Memory": 0.0,
    "Disk": 0.0,

    "Disk_Read": 0.0,
    "Disk_Write": 0.0,

    "CPU_Frequency": 0.0,

    "Network_Download": 0.0,
    "Network_Upload": 0.0,

    "Process_Count": 0,

    "Remote_Connections": 0,
    "Established_Connections": 0,
    "Listening_Connections": 0,

    "Sensitive_Files": 0,

    "IF_Anomaly": 0,
    "LOF_Anomaly": 0,
    "Anomaly": 0,

    "IF_Score": 0.0,
    "LOF_Score": 0.0,

    "IF_Anomaly_Intensity": 0.0,
    "LOF_Anomaly_Intensity": 0.0,

    "Anomaly_Confidence": 0.0,

    "Strongest_Feature": "",
    "Strongest_Feature_Deviation": 0.0,

    "Risk": "NORMAL",
    "Severity": "INFO",
    "Risk_Score": 0,

    "Network_Level": "NORMAL",
    "Process_Level": "NORMAL",

    "Privacy_Event": 0,

    "Potential_Data_Exfiltration": 0,
    "Potential_Camera_Risk": 0,

    "Behavioral_Adjustment": 0,

    "Model_Health": "UNKNOWN",
    "Training_Samples": 0,
}


# ============================================================
# DATA DIRECTORY
# ============================================================

def _ensure_data_dir() -> None:
    """
    Ensure AURA's data directory exists.
    """

    DATA_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


# ============================================================
# SAFE NUMERIC CONVERSION
# ============================================================

def _safe_float(
    value: Any,
    default: float = 0.0,
) -> float:
    """
    Convert a value to float safely.
    """

    try:

        number = float(value)

        if pd.isna(number):
            return default

        return number

    except (
        TypeError,
        ValueError,
    ):

        return default


def _safe_int(
    value: Any,
    default: int = 0,
) -> int:
    """
    Convert a value to integer safely.
    """

    try:

        number = int(
            float(value)
        )

        return number

    except (
        TypeError,
        ValueError,
    ):

        return default


def _safe_text(
    value: Any,
    default: str = "",
) -> str:
    """
    Convert a value to a clean string.
    """

    if value is None:
        return default

    try:

        if pd.isna(value):
            return default

    except (TypeError, ValueError):
        pass

    return str(
        value
    )


# ============================================================
# EVENT ID
# ============================================================

def _generate_event_id() -> str:
    """
    Generate a human-readable event identifier.
    """

    timestamp = pd.Timestamp.now()

    return timestamp.strftime(
        "AURA-%Y%m%d-%H%M%S-%f"
    )[:-3]


# ============================================================
# BASELINE STORAGE
# ============================================================

def save_baseline(
    data,
    filename: Optional[str] = None,
) -> Path:
    """
    Save the ML baseline.

    Expected columns:

        CPU
        Net
        Cam
    """

    _ensure_data_dir()

    path = (
        Path(filename)
        if filename
        else BASELINE_FILE
    )

    rows = list(
        data
    )

    dataframe = pd.DataFrame(
        rows,
        columns=BASELINE_COLUMNS,
    )

    # Numeric validation.
    for column in BASELINE_COLUMNS:

        dataframe[column] = pd.to_numeric(
            dataframe[column],
            errors="coerce",
        )

    dataframe = dataframe.dropna(
        subset=BASELINE_COLUMNS
    )

    if dataframe.empty:

        raise ValueError(
            "Cannot save an empty AURA baseline."
        )

    dataframe.to_csv(
        path,
        index=False,
    )

    return path


# ============================================================
# BASELINE LOADING
# ============================================================

def load_baseline(
    filename: Optional[str] = None,
) -> pd.DataFrame:
    """
    Load the AURA ML baseline.

    Returns an empty DataFrame when no baseline exists.
    """

    path = (
        Path(filename)
        if filename
        else BASELINE_FILE
    )

    if not path.exists():

        return pd.DataFrame(
            columns=BASELINE_COLUMNS
        )

    try:

        dataframe = pd.read_csv(
            path
        )

    except (
        OSError,
        pd.errors.EmptyDataError,
        pd.errors.ParserError,
    ):

        return pd.DataFrame(
            columns=BASELINE_COLUMNS
        )

    # Make sure all required columns exist.
    for column in BASELINE_COLUMNS:

        if column not in dataframe.columns:

            dataframe[column] = (
                DEFAULTS[column]
            )

    dataframe = dataframe[
        BASELINE_COLUMNS
    ]

    # Convert everything to numeric.
    for column in BASELINE_COLUMNS:

        dataframe[column] = pd.to_numeric(
            dataframe[column],
            errors="coerce",
        )

    dataframe = dataframe.dropna()

    return dataframe.reset_index(
        drop=True
    )


# ============================================================
# LOG ROW NORMALIZATION
# ============================================================

def _normalize_log_row(
    values: dict[str, Any],
) -> dict[str, Any]:
    """
    Create a complete AURA log row.

    Missing fields receive safe defaults.

    This is what allows old code and new code to coexist.
    """

    row = dict(
        DEFAULTS
    )

    row.update(
        values
    )

    # --------------------------------------------------------
    # Numeric fields
    # --------------------------------------------------------

    float_fields = {

        "CPU",
        "Net",

        "Memory",
        "Disk",

        "Disk_Read",
        "Disk_Write",

        "CPU_Frequency",

        "Network_Download",
        "Network_Upload",

        "IF_Score",
        "LOF_Score",

        "IF_Anomaly_Intensity",
        "LOF_Anomaly_Intensity",

        "Anomaly_Confidence",

        "Strongest_Feature_Deviation",

    }

    int_fields = {

        "Cam",

        "Process_Count",

        "Remote_Connections",
        "Established_Connections",
        "Listening_Connections",

        "Sensitive_Files",

        "IF_Anomaly",
        "LOF_Anomaly",
        "Anomaly",

        "Risk_Score",

        "Privacy_Event",

        "Potential_Data_Exfiltration",
        "Potential_Camera_Risk",

        "Behavioral_Adjustment",

        "Training_Samples",

    }

    for field in float_fields:

        row[field] = _safe_float(
            row[field]
        )

    for field in int_fields:

        row[field] = _safe_int(
            row[field]
        )

    # --------------------------------------------------------
    # Text fields
    # --------------------------------------------------------

    text_fields = {

        "Timestamp",
        "Event_ID",

        "Strongest_Feature",

        "Risk",
        "Severity",

        "Network_Level",
        "Process_Level",

        "Model_Health",

    }

    for field in text_fields:

        row[field] = _safe_text(
            row[field],
            DEFAULTS[field],
        )

    return row


# ============================================================
# LEGACY LOG MIGRATION
# ============================================================

def _migrate_logs(
    path: Path,
) -> pd.DataFrame:
    """
    Read an existing AURA CSV and upgrade it to the current
    schema.

    Existing historical data is preserved.

    New fields receive safe defaults.
    """

    if not path.exists():

        return pd.DataFrame(
            columns=COLUMNS
        )

    try:

        dataframe = pd.read_csv(
            path
        )

    except (
        OSError,
        pd.errors.EmptyDataError,
        pd.errors.ParserError,
    ):

        return pd.DataFrame(
            columns=COLUMNS
        )

    # --------------------------------------------------------
    # Add missing columns
    # --------------------------------------------------------

    for column in COLUMNS:

        if column not in dataframe.columns:

            dataframe[column] = (
                DEFAULTS[column]
            )

    # --------------------------------------------------------
    # Remove unknown columns from the persistent schema.
    #
    # This prevents old experimental fields from breaking
    # future versions of AURA.
    # --------------------------------------------------------

    dataframe = dataframe[
        COLUMNS
    ]

    # --------------------------------------------------------
    # Normalize historical values
    # --------------------------------------------------------

    for column in COLUMNS:

        if column in {
            "Timestamp",
            "Event_ID",
            "Risk",
            "Severity",
            "Network_Level",
            "Process_Level",
            "Strongest_Feature",
            "Model_Health",
        }:

            continue

        if column in {
            "Cam",
            "Process_Count",
            "Remote_Connections",
            "Established_Connections",
            "Listening_Connections",
            "Sensitive_Files",
            "IF_Anomaly",
            "LOF_Anomaly",
            "Anomaly",
            "Risk_Score",
            "Privacy_Event",
            "Potential_Data_Exfiltration",
            "Potential_Camera_Risk",
            "Behavioral_Adjustment",
            "Training_Samples",
        }:

            dataframe[column] = pd.to_numeric(
                dataframe[column],
                errors="coerce",
            ).fillna(
                DEFAULTS[column]
            ).astype(int)

        else:

            dataframe[column] = pd.to_numeric(
                dataframe[column],
                errors="coerce",
            ).fillna(
                DEFAULTS[column]
            )

    return dataframe


# ============================================================
# APPEND SECURITY EVENT
# ============================================================

def append_log(
    cpu: float,
    net: float,
    cam: int,

    if_anomaly: int = 0,
    lof_anomaly: int = 0,
    anomaly: int = 0,

    risk: str = "NORMAL",

    process_count: int = 0,
    remote_connections: int = 0,
    sensitive_files: int = 0,

    risk_score: int = 0,
    network_level: str = "NORMAL",

    privacy_event: int = 0,
    potential_data_exfiltration: int = 0,

    filename: Optional[str] = None,

    # --------------------------------------------------------
    # Extended telemetry
    # --------------------------------------------------------

    memory: float = 0.0,
    disk: float = 0.0,

    disk_read: float = 0.0,
    disk_write: float = 0.0,

    cpu_frequency: float = 0.0,

    network_download: float = 0.0,
    network_upload: float = 0.0,

    established_connections: int = 0,
    listening_connections: int = 0,

    # --------------------------------------------------------
    # AI intelligence
    # --------------------------------------------------------

    if_score: float = 0.0,
    lof_score: float = 0.0,

    if_anomaly_intensity: float = 0.0,
    lof_anomaly_intensity: float = 0.0,

    anomaly_confidence: float = 0.0,

    strongest_feature: str = "",
    strongest_feature_deviation: float = 0.0,

    # --------------------------------------------------------
    # Risk intelligence
    # --------------------------------------------------------

    severity: str = "INFO",

    process_level: str = "NORMAL",

    potential_camera_risk: int = 0,

    behavioral_adjustment: int = 0,

    # --------------------------------------------------------
    # Model information
    # --------------------------------------------------------

    model_health: str = "UNKNOWN",

    training_samples: int = 0,

) -> Path:
    """
    Append one complete AURA security event.

    The function remains backward-compatible with the original
    AURA append_log() interface.
    """

    _ensure_data_dir()

    path = (
        Path(filename)
        if filename
        else LOG_FILE
    )

    # --------------------------------------------------------
    # Build row
    # --------------------------------------------------------

    row = _normalize_log_row({

        "Timestamp": pd.Timestamp.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        ),

        "Event_ID": _generate_event_id(),

        "CPU": cpu,
        "Net": net,
        "Cam": cam,

        "Memory": memory,
        "Disk": disk,

        "Disk_Read": disk_read,
        "Disk_Write": disk_write,

        "CPU_Frequency": cpu_frequency,

        "Network_Download": network_download,
        "Network_Upload": network_upload,

        "Process_Count": process_count,

        "Remote_Connections": remote_connections,
        "Established_Connections": (
            established_connections
        ),
        "Listening_Connections": (
            listening_connections
        ),

        "Sensitive_Files": sensitive_files,

        "IF_Anomaly": if_anomaly,
        "LOF_Anomaly": lof_anomaly,
        "Anomaly": anomaly,

        "IF_Score": if_score,
        "LOF_Score": lof_score,

        "IF_Anomaly_Intensity": (
            if_anomaly_intensity
        ),
        "LOF_Anomaly_Intensity": (
            lof_anomaly_intensity
        ),

        "Anomaly_Confidence": (
            anomaly_confidence
        ),

        "Strongest_Feature": (
            strongest_feature
        ),

        "Strongest_Feature_Deviation": (
            strongest_feature_deviation
        ),

        "Risk": risk,

        "Severity": severity,

        "Risk_Score": risk_score,

        "Network_Level": network_level,

        "Process_Level": process_level,

        "Privacy_Event": privacy_event,

        "Potential_Data_Exfiltration": (
            potential_data_exfiltration
        ),

        "Potential_Camera_Risk": (
            potential_camera_risk
        ),

        "Behavioral_Adjustment": (
            behavioral_adjustment
        ),

        "Model_Health": model_health,

        "Training_Samples": training_samples,
    })

    # --------------------------------------------------------
    # Handle existing logs
    # --------------------------------------------------------

    if path.exists():

        existing = _migrate_logs(
            path
        )

        new_row = pd.DataFrame(
            [row],
            columns=COLUMNS,
        )

        combined = pd.concat(
            [
                existing,
                new_row,
            ],
            ignore_index=True,
        )

        combined.to_csv(
            path,
            index=False,
        )

    else:

        dataframe = pd.DataFrame(
            [row],
            columns=COLUMNS,
        )

        dataframe.to_csv(
            path,
            index=False,
        )

    # --------------------------------------------------------
    # Also record in modern SQLite storage engine
    # --------------------------------------------------------
    try:
        from aura.core.paths import get_paths
        from aura.models.types import PrivacyHardwareStatus, SecurityEvent, TelemetrySnapshot
        from aura.storage.sqlite import StorageEngine

        db_path = get_paths().database_path
        storage = StorageEngine(db_path)

        t_snap = TelemetrySnapshot(
            timestamp=row["Timestamp"],
            cpu_percent=float(row["CPU"]),
            memory_percent=float(row["Memory"]),
            disk_percent=float(row["Disk"]),
            disk_io_write_kbps=float(row["Disk_Write"]),
            net_upload_kbps=float(row["Net_Upload"]),
            net_download_kbps=float(row["Network_Download"]),
            process_count=int(row["Process_Count"]),
            established_connections=int(row["Established_Connections"]),
            listening_connections=int(row["Listening_Connections"]),
            remote_connections=int(row["Remote_Connections"]),
            camera_status=PrivacyHardwareStatus.AVAILABLE if int(row["Cam"]) else PrivacyHardwareStatus.NOT_DETECTED,
        )
        storage.record_telemetry(t_snap)

        sec_evt = SecurityEvent(
            event_id=row["Event_ID"],
            timestamp=row["Timestamp"],
            event_type="SCAN_EVENT",
            severity=row["Severity"],
            risk_score=float(row["Risk_Score"]),
            source="logger.append_log",
            summary=f"Scan record: {row['Severity']} (Risk Score: {row['Risk_Score']})",
        )
        storage.record_security_event(sec_evt)
    except Exception:
        pass

    return path


# ============================================================
# LOAD SECURITY LOGS
# ============================================================

def load_logs(
    filename: Optional[str] = None,
) -> pd.DataFrame:
    """
    Load AURA security logs using the current schema.

    Older logs are automatically upgraded in memory.
    """

    path = (
        Path(filename)
        if filename
        else LOG_FILE
    )

    if not path.exists():

        return pd.DataFrame(
            columns=COLUMNS
        )

    dataframe = _migrate_logs(
        path
    )

    # --------------------------------------------------------
    # Timestamp conversion
    # --------------------------------------------------------

    if "Timestamp" in dataframe.columns:

        dataframe["Timestamp"] = pd.to_datetime(
            dataframe["Timestamp"],
            errors="coerce",
        )

    return dataframe.reset_index(
        drop=True
    )


# ============================================================
# SAVE DATA — LEGACY COMPATIBILITY
# ============================================================

def save_data(
    data,
    filename: str = "data/system_logs.csv",
):
    """
    Backward-compatible helper.

    Historically this function saved CPU/Net/Cam data.
    It is retained so older project code does not break.
    """

    path = Path(
        filename
    )

    if not path.is_absolute():

        path = (
            BASE_DIR / path
        )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    dataframe = pd.DataFrame(
        data,
        columns=BASELINE_COLUMNS,
    )

    dataframe.to_csv(
        path,
        index=False,
    )

    return path


# ============================================================
# LOG STATISTICS
# ============================================================

def get_log_statistics(
    filename: Optional[str] = None,
) -> dict[str, Any]:
    """
    Generate a compact summary of AURA's historical events.

    Useful for the future Analytics dashboard.
    """

    logs = load_logs(
        filename
    )

    if logs.empty:

        return {
            "total_events": 0,
            "anomalies": 0,
            "privacy_events": 0,
            "high_risk_events": 0,
            "critical_events": 0,
            "average_risk_score": 0.0,
            "maximum_risk_score": 0,
        }

    risk_scores = pd.to_numeric(
        logs["Risk_Score"],
        errors="coerce",
    ).fillna(0)

    risks = (
        logs["Risk"]
        .astype(str)
        .str.upper()
    )

    anomalies = pd.to_numeric(
        logs["Anomaly"],
        errors="coerce",
    ).fillna(0)

    privacy_events = pd.to_numeric(
        logs["Privacy_Event"],
        errors="coerce",
    ).fillna(0)

    return {
        "total_events": int(
            len(logs)
        ),

        "anomalies": int(
            anomalies.sum()
        ),

        "privacy_events": int(
            privacy_events.sum()
        ),

        "high_risk_events": int(
            risks.isin(
                [
                    "HIGH",
                    "CRITICAL",
                ]
            ).sum()
        ),

        "critical_events": int(
            (
                risks == "CRITICAL"
            ).sum()
        ),

        "average_risk_score": round(
            float(
                risk_scores.mean()
            ),
            2,
        ),

        "maximum_risk_score": int(
            risk_scores.max()
        ),
    }


# ============================================================
# CLEAR LOGS
# ============================================================

def clear_logs(
    filename: Optional[str] = None,
) -> Path:
    """
    Clear historical security events while preserving the
    AURA logging schema.

    Useful during development/testing.
    """

    _ensure_data_dir()

    path = (
        Path(filename)
        if filename
        else LOG_FILE
    )

    pd.DataFrame(
        columns=COLUMNS
    ).to_csv(
        path,
        index=False,
    )

    return path