"""
AURA Production API & Agent Contract Specification.

Exports typed Pydantic models and enums for agents, health reporting,
REST API requests/responses, authentication, and WebSocket streams.
"""

from aura.contracts.agent import (
    AgentHealthResponse,
    AgentState,
    AgentStatus,
    CollectionHealth,
    DetectionHealth,
    DiagnosticsHealth,
    SensorHealthItem,
    StorageHealth,
)
from aura.contracts.api import (
    EventAcknowledgeRequest,
    EventQuery,
    EvidenceItem,
    MonitoringStartRequest,
    MonitoringStopRequest,
    PaginatedResponse,
    PaginationQuery,
    RiskResponse,
    ScanRequest,
    ScanStage,
    ScanState,
    ScanStatusResponse,
    SecurityEventResponse,
    TelemetryHistoryQuery,
    TelemetryResponse,
)
from aura.contracts.auth import (
    AuthScope,
    AuthSessionStatus,
    AuthTokenClaims,
    SessionHandshakeRequest,
    SessionHandshakeResponse,
)
from aura.contracts.errors import (
    ApiErrorResponse,
    ErrorCode,
)
from aura.contracts.stream import (
    AgentStatusChangeMessage,
    BaseStreamMessage,
    ErrorStreamMessage,
    HeartbeatMessage,
    LiveStreamMessage,
    ScanProgressMessage,
    SecurityEventMessage,
    SensorHealthChangeMessage,
    StreamMessageType,
    TelemetryTickMessage,
)

__all__ = [
    "AgentHealthResponse",
    "AgentState",
    "AgentStatus",
    "AgentStatusChangeMessage",
    "ApiErrorResponse",
    "AuthScope",
    "AuthSessionStatus",
    "AuthTokenClaims",
    "BaseStreamMessage",
    "CollectionHealth",
    "DetectionHealth",
    "DiagnosticsHealth",
    "ErrorCode",
    "ErrorStreamMessage",
    "EventAcknowledgeRequest",
    "EventQuery",
    "EvidenceItem",
    "HeartbeatMessage",
    "LiveStreamMessage",
    "MonitoringStartRequest",
    "MonitoringStopRequest",
    "PaginatedResponse",
    "PaginationQuery",
    "RiskResponse",
    "ScanProgressMessage",
    "ScanRequest",
    "ScanStage",
    "ScanState",
    "ScanStatusResponse",
    "SecurityEventMessage",
    "SecurityEventResponse",
    "SensorHealthChangeMessage",
    "SensorHealthItem",
    "SessionHandshakeRequest",
    "SessionHandshakeResponse",
    "StorageHealth",
    "StreamMessageType",
    "TelemetryHistoryQuery",
    "TelemetryResponse",
    "TelemetryTickMessage",
]
